apiVersion: vi
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: result-app-pod-app-pod
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80