name: Install Java

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Install Java
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-j
